server:
  port: 8080

oracle:
  ucp:
    jdbc:
      PoolDataSource:
        atp:
          connectionFactoryClassName: oracle.jdbc.pool.OracleDataSource
          tnsNetServiceName: "${atp.db.tnsNetServiceName}"
          user: "${atp.db.user}"
          password: "${atp.db.password}"

oci:
  atp:
    ocid: "${oci.properties.atp-ocid}"
    walletPassword: "${oci.properties.atp-walletPassword}"
  auth-strategies: instance-principals

